version: "3"

services:
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./static/uploads:/app/static/uploads
      - ./database.db:/app/database.db
    environment:
      - SECRET_KEY=your-secret-key-32-chars-long
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
